version: '3'
services:
  token_management:
    build: ./map_management
    ports:
        - "127.0.0.1:7804:8000"
    restart: on-failure
    volumes:
        - .:/src
        - /etc/haproxy/maps:/etc/haproxy/maps